### ISSUE TITLE
event-log-manager.ps1 broken CSV output when XML has commas 

### ISSUE THREAD

**Issue by maysara** [jagilber/powershellScripts#2]
The csv output is broken when there are commas in the event XML.

**Comment by maysara** [comment]
I propose to quote all csv fields.

This goes over them as an array, escapes double quotes, and padds them with doublequotes and seperates them with doublequotes and a comma

$outputEntry = '"{0}"' -f (($($event.TimeCreated.ToString("MM/dd/yyyy,hh:mm:ss.ffffff tt")),$($event.Id),
                                $($event.LevelDisplayName),$($event.ProviderName),$($event.ProcessId),$($event.ThreadId),
                                $($description) -replace '"','""') -join """,""")

**Comment by jagilber** [comment]
@maysara  thanks for reporting. updated script..
